### ISSUE TITLE
Size of Hall of Fame checkbox differ if Logo checkbox is checked or not.

### ISSUE THREAD

**Issue by GuthrieW** [GuthrieW/shl-trading-cards#78]
Steps to Reproduce: Collection -> Filter on type

Device (PC/Mac/Linux/iPhone/Android/Other): Windows 10

Web Browser (Chrome/Firefox/Safari/Edge/Brave/Other): Chrome

Other Information:

Image of Bug: https://cdn.discordapp.com/attachments/911166509026541679/957977322437378058/unknown.png

**Comment by esilverm** [comment]
we can just rename "hall of fame" to "hof" in this checkbox dropdown

**Comment by esilverm** [comment]
To build on this bug -
Description: The dropdown by default appears to have both checked, but when you select one to "uncheck" it, it actually checks it and filters out the other one. So if you want to filter your collection, and you click on logos to filter out logos, you will see only the logo cards. Once you start filtering then the check boxes work as expected. In order to view all your cards again though you have to uncheck both boxes, but once all the cards are back it switches to again display both boxes as checked.

Steps to Reproduce: Collection -> Filter on type

Device (PC/Mac/Linux/iPhone/Android/Other): Windows 10

Web Browser (Chrome/Firefox/Safari/Edge/Brave/Other): Chrome

Other Information:

I've attached a video showing the issue because it's easier than using pictures.
[https://www.dropbox.com/s/kmypl4zq6es1sy...4.mkv?dl=0](https://www.dropbox.com/s/kmypl4zq6es1syx/2022-03-28%2012-37-04.mkv?dl=0)

## Evan's Comments
I agree that this isn't intuitive and we should probably change the functionality. Shouldn't be too hard to do.

**Comment by esilverm** [comment]
This is fixed
